language: ruby

addons:
  postgresql: "9.4"

services:
  - postgresql
  - redis-server

rvm:
  - ruby-3.0.0-preview1

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head

before_install:
  - sed -i "s/gems.ruby-china.org/rubygems.org/g" Gemfile.lock
  - psql -c "CREATE USER \"admin\" WITH CREATEDB PASSWORD 'admin';" -U postgres
  - psql -c "create database \"homeland-test\" WITH OWNER=\"admin\";" -U postgres
  - sed -i "s/SETUP_REDIS_HOST/127.0.0.1/g" config/redis.yml
  - sed -i "s/SETUP_REDIS_PORT/6379/g" config/redis.yml

before_script:
  - RAILS_ENV=test bundle exec rake db:migrate

script:
  - bundle exec rubocop .
  - RUBYOPT=W0 RAILS_ENV=test bundle exec rails test
