# Options here can still be overridden by cmd line args.
#   sidekiq -C sidekiq.yml
---
:concurrency: 20
:pidfile: tmp/pids/sidekiq.pid
:logfile: log/sidekiq.log
:queues:
  - [notifications, 100]
  - [http_request, 50]
  - [mailer, 5]
  - [default, 3]
