---
address: 0.0.0.0
pid: tmp/pids/thin.pid
timeout: 120
port: 7000
log: log/thin.log
max_conns: 20480
require: []

max_persistent_conns: 4048
environment: production
servers: 2
daemonize: true
chdir: /home/ruby/www/ruby-china/current

